spring.application.name=member_management

# DB PostgreSQL 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/training
spring.datasource.username=docker
spring.datasource.password=docker
spring.jpa.open-in-view=True

# SQLをログ出力		
logging.level.org.hibernate.SQL=trace		
# SQLのバインドパラメーターをログ出力		
logging.level.org.hibernate.type=trace		
logging.level.org.hibernate.orm.jdbc.bind=trace		
# SELECT文の結果をログ出力		
logging.level.org.hibernate.orm.jdbc.extract=debug		
# SQL整形		
spring.jpa.properties.hibernate.format_sql=true	